export type EmojiItem = {
    e: string;
    n: string;
    k?: string;
};

export type EmojiCategory = {
    id: string;
    label: string;
    icon: string;
    emojis: EmojiItem[];
};

export const EMOJI_CATEGORIES: EmojiCategory[] = [
    {
        id: 'smileys',
        label: 'Smileys',
        icon: '😀',
        emojis: [
            { e: '😀', n: 'grinning', k: 'happy smile' },
            { e: '😃', n: 'smiley', k: 'happy' },
            { e: '😄', n: 'smile', k: 'happy laugh' },
            { e: '😁', n: 'grin', k: 'happy' },
            { e: '😆', n: 'laughing', k: 'happy lol' },
            { e: '😅', n: 'sweat smile', k: 'relief' },
            { e: '🤣', n: 'rofl', k: 'lol laugh' },
            { e: '😂', n: 'joy', k: 'tears laugh' },
            { e: '🙂', n: 'slightly smiling', k: 'smile' },
            { e: '😉', n: 'wink', k: 'flirt' },
            { e: '😊', n: 'blush', k: 'happy' },
            { e: '😇', n: 'innocent', k: 'angel' },
            { e: '🥰', n: 'smiling hearts', k: 'love' },
            { e: '😍', n: 'heart eyes', k: 'love' },
            { e: '🤩', n: 'star struck', k: 'wow' },
            { e: '😘', n: 'kissing heart', k: 'love' },
            { e: '😗', n: 'kissing', k: 'love' },
            { e: '😚', n: 'kissing closed eyes', k: 'love' },
            { e: '😋', n: 'yum', k: 'tasty' },
            { e: '😛', n: 'stuck out tongue', k: 'playful' },
            { e: '😜', n: 'stuck out tongue wink', k: 'playful' },
            { e: '🤪', n: 'zany', k: 'crazy' },
            { e: '😝', n: 'stuck out tongue closed', k: 'playful' },
            { e: '🤑', n: 'money mouth', k: 'rich' },
            { e: '🤗', n: 'hugs', k: 'hug' },
            { e: '🤭', n: 'hand over mouth', k: 'oops' },
            { e: '🤫', n: 'shushing', k: 'quiet' },
            { e: '🤔', n: 'thinking', k: 'hmm' },
            { e: '🤐', n: 'zipper mouth', k: 'quiet' },
            { e: '🤨', n: 'raised eyebrow', k: 'skeptical' },
            { e: '😐', n: 'neutral', k: 'meh' },
            { e: '😑', n: 'expressionless', k: 'blank' },
            { e: '😶', n: 'no mouth', k: 'silent' },
            { e: '😏', n: 'smirk', k: 'smug' },
            { e: '😒', n: 'unamused', k: 'meh' },
            { e: '🙄', n: 'eye roll', k: 'whatever' },
            { e: '😬', n: 'grimacing', k: 'awkward' },
            { e: '😌', n: 'relieved', k: 'calm' },
            { e: '😔', n: 'pensive', k: 'sad' },
            { e: '😪', n: 'sleepy', k: 'tired' },
            { e: '🤤', n: 'drooling', k: 'hungry' },
            { e: '😴', n: 'sleeping', k: 'tired zzz' },
            { e: '😷', n: 'mask', k: 'sick' },
            { e: '🤒', n: 'thermometer', k: 'sick' },
            { e: '🤕', n: 'head bandage', k: 'hurt' },
            { e: '🤢', n: 'nauseated', k: 'sick' },
            { e: '🤮', n: 'vomiting', k: 'sick' },
            { e: '🥵', n: 'hot', k: 'heat' },
            { e: '🥶', n: 'cold', k: 'freeze' },
            { e: '🥴', n: 'woozy', k: 'dizzy' },
            { e: '😵', n: 'dizzy face', k: 'dead' },
            { e: '🤯', n: 'exploding head', k: 'mind blown' },
            { e: '🤠', n: 'cowboy', k: 'hat' },
            { e: '🥳', n: 'partying', k: 'celebrate' },
            { e: '😎', n: 'sunglasses', k: 'cool' },
            { e: '🤓', n: 'nerd', k: 'glasses' },
            { e: '🧐', n: 'monocle', k: 'inspect' },
            { e: '😕', n: 'confused', k: 'huh' },
            { e: '😟', n: 'worried', k: 'sad' },
            { e: '🙁', n: 'slightly frowning', k: 'sad' },
            { e: '😮', n: 'open mouth', k: 'surprise' },
            { e: '😯', n: 'hushed', k: 'surprise' },
            { e: '😲', n: 'astonished', k: 'shock' },
            { e: '😳', n: 'flushed', k: 'embarrassed' },
            { e: '🥺', n: 'pleading', k: 'puppy eyes' },
            { e: '😦', n: 'frowning', k: 'sad' },
            { e: '😧', n: 'anguished', k: 'pain' },
            { e: '😨', n: 'fearful', k: 'scared' },
            { e: '😰', n: 'anxious', k: 'sweat' },
            { e: '😥', n: 'sad but relieved', k: 'sweat' },
            { e: '😢', n: 'cry', k: 'tear sad' },
            { e: '😭', n: 'sob', k: 'cry sad' },
            { e: '😱', n: 'scream', k: 'fear' },
            { e: '😖', n: 'confounded', k: 'upset' },
            { e: '😣', n: 'persevering', k: 'struggle' },
            { e: '😞', n: 'disappointed', k: 'sad' },
            { e: '😓', n: 'downcast', k: 'sweat' },
            { e: '😩', n: 'weary', k: 'tired' },
            { e: '😫', n: 'tired', k: 'exhausted' },
            { e: '🥱', n: 'yawning', k: 'tired' },
            { e: '😤', n: 'triumph', k: 'angry steam' },
            { e: '😡', n: 'pouting', k: 'angry' },
            { e: '😠', n: 'angry', k: 'mad' },
            { e: '🤬', n: 'cursing', k: 'angry swear' },
            { e: '😈', n: 'smiling devil', k: 'evil' },
            { e: '👿', n: 'angry devil', k: 'evil' },
            { e: '💀', n: 'skull', k: 'dead' },
            { e: '☠️', n: 'skull crossbones', k: 'danger' },
            { e: '💩', n: 'poop', k: 'poo' },
            { e: '🤡', n: 'clown', k: 'funny' },
            { e: '👹', n: 'ogre', k: 'monster' },
            { e: '👺', n: 'goblin', k: 'monster' },
            { e: '👻', n: 'ghost', k: 'halloween' },
            { e: '👽', n: 'alien', k: 'ufo' },
            { e: '👾', n: 'space invader', k: 'game' },
            { e: '🤖', n: 'robot', k: 'bot' },
            { e: '🎃', n: 'jack o lantern', k: 'halloween' },
            { e: '😺', n: 'smiley cat', k: 'cat' },
            { e: '😸', n: 'smile cat', k: 'cat' },
            { e: '😹', n: 'joy cat', k: 'cat laugh' },
            { e: '😻', n: 'heart eyes cat', k: 'cat love' },
            { e: '😼', n: 'smirk cat', k: 'cat' },
            { e: '😽', n: 'kissing cat', k: 'cat' },
            { e: '🙀', n: 'scream cat', k: 'cat' },
            { e: '😿', n: 'crying cat', k: 'cat sad' },
            { e: '😾', n: 'pouting cat', k: 'cat angry' },
        ],
    },
    {
        id: 'gestures',
        label: 'Gestures',
        icon: '👋',
        emojis: [
            { e: '👋', n: 'wave', k: 'hello bye' },
            { e: '🤚', n: 'raised back of hand', k: 'stop' },
            { e: '🖐️', n: 'hand splayed', k: 'five' },
            { e: '✋', n: 'raised hand', k: 'stop' },
            { e: '🖖', n: 'vulcan', k: 'spock' },
            { e: '👌', n: 'ok hand', k: 'okay' },
            { e: '🤌', n: 'pinched fingers', k: 'italian' },
            { e: '🤏', n: 'pinching hand', k: 'small' },
            { e: '✌️', n: 'victory', k: 'peace' },
            { e: '🤞', n: 'crossed fingers', k: 'luck' },
            { e: '🤟', n: 'love you gesture', k: 'ily' },
            { e: '🤘', n: 'metal', k: 'rock' },
            { e: '🤙', n: 'call me', k: 'shaka' },
            { e: '👈', n: 'point left', k: 'left' },
            { e: '👉', n: 'point right', k: 'right' },
            { e: '👆', n: 'point up', k: 'up' },
            { e: '👇', n: 'point down', k: 'down' },
            { e: '☝️', n: 'index pointing up', k: 'up' },
            { e: '👍', n: 'thumbs up', k: 'like yes' },
            { e: '👎', n: 'thumbs down', k: 'dislike no' },
            { e: '✊', n: 'fist', k: 'power' },
            { e: '👊', n: 'punch', k: 'fist' },
            { e: '🤛', n: 'left facing fist', k: 'bump' },
            { e: '🤜', n: 'right facing fist', k: 'bump' },
            { e: '👏', n: 'clap', k: 'applause' },
            { e: '🙌', n: 'raised hands', k: 'hooray' },
            { e: '👐', n: 'open hands', k: 'hug' },
            { e: '🤲', n: 'palms up', k: 'pray' },
            { e: '🤝', n: 'handshake', k: 'deal' },
            { e: '🙏', n: 'pray', k: 'please thanks' },
            { e: '✍️', n: 'writing hand', k: 'write' },
            { e: '💅', n: 'nail polish', k: 'nails' },
            { e: '🤳', n: 'selfie', k: 'phone' },
            { e: '💪', n: 'muscle', k: 'strong flex' },
            { e: '🦾', n: 'mechanical arm', k: 'robot' },
            { e: '🦿', n: 'mechanical leg', k: 'robot' },
            { e: '🦵', n: 'leg', k: 'kick' },
            { e: '🦶', n: 'foot', k: 'kick' },
            { e: '👂', n: 'ear', k: 'hear' },
            { e: '👃', n: 'nose', k: 'smell' },
            { e: '🧠', n: 'brain', k: 'think' },
            { e: '👀', n: 'eyes', k: 'look see' },
            { e: '👁️', n: 'eye', k: 'see' },
            { e: '👅', n: 'tongue', k: 'taste' },
            { e: '👄', n: 'lips', k: 'kiss' },
            { e: '💋', n: 'kiss mark', k: 'lipstick' },
            { e: '🩸', n: 'drop of blood', k: 'blood' },
        ],
    },
    {
        id: 'hearts',
        label: 'Hearts',
        icon: '❤️',
        emojis: [
            { e: '❤️', n: 'red heart', k: 'love' },
            { e: '🧡', n: 'orange heart', k: 'love' },
            { e: '💛', n: 'yellow heart', k: 'love' },
            { e: '💚', n: 'green heart', k: 'love' },
            { e: '💙', n: 'blue heart', k: 'love' },
            { e: '💜', n: 'purple heart', k: 'love' },
            { e: '🖤', n: 'black heart', k: 'love' },
            { e: '🤍', n: 'white heart', k: 'love' },
            { e: '🤎', n: 'brown heart', k: 'love' },
            { e: '💔', n: 'broken heart', k: 'sad' },
            { e: '❣️', n: 'heart exclamation', k: 'love' },
            { e: '💕', n: 'two hearts', k: 'love' },
            { e: '💞', n: 'revolving hearts', k: 'love' },
            { e: '💓', n: 'beating heart', k: 'love' },
            { e: '💗', n: 'growing heart', k: 'love' },
            { e: '💖', n: 'sparkling heart', k: 'love' },
            { e: '💘', n: 'heart arrow', k: 'cupid' },
            { e: '💝', n: 'heart ribbon', k: 'gift' },
            { e: '💟', n: 'heart decoration', k: 'love' },
            { e: '💯', n: 'hundred', k: 'perfect score' },
            { e: '💥', n: 'collision', k: 'boom' },
            { e: '💫', n: 'dizzy', k: 'star' },
            { e: '💦', n: 'sweat droplets', k: 'water' },
            { e: '💨', n: 'dash', k: 'fast' },
            { e: '🕳️', n: 'hole', k: 'empty' },
            { e: '💣', n: 'bomb', k: 'explode' },
            { e: '💬', n: 'speech balloon', k: 'chat' },
            { e: '👁️‍🗨️', n: 'eye in speech bubble', k: 'witness' },
            { e: '🗨️', n: 'left speech bubble', k: 'chat' },
            { e: '🗯️', n: 'right anger bubble', k: 'mad' },
            { e: '💭', n: 'thought balloon', k: 'think' },
            { e: '💤', n: 'zzz', k: 'sleep' },
        ],
    },
    {
        id: 'animals',
        label: 'Animals',
        icon: '🐶',
        emojis: [
            { e: '🐶', n: 'dog', k: 'puppy pet' },
            { e: '🐱', n: 'cat', k: 'kitten pet' },
            { e: '🐭', n: 'mouse', k: 'rodent' },
            { e: '🐹', n: 'hamster', k: 'pet' },
            { e: '🐰', n: 'rabbit', k: 'bunny' },
            { e: '🦊', n: 'fox', k: 'animal' },
            { e: '🐻', n: 'bear', k: 'animal' },
            { e: '🐼', n: 'panda', k: 'bear' },
            { e: '🐨', n: 'koala', k: 'animal' },
            { e: '🐯', n: 'tiger', k: 'animal' },
            { e: '🦁', n: 'lion', k: 'animal' },
            { e: '🐮', n: 'cow', k: 'animal' },
            { e: '🐷', n: 'pig', k: 'animal' },
            { e: '🐸', n: 'frog', k: 'animal' },
            { e: '🐵', n: 'monkey face', k: 'animal' },
            { e: '🙈', n: 'see no evil', k: 'monkey' },
            { e: '🙉', n: 'hear no evil', k: 'monkey' },
            { e: '🙊', n: 'speak no evil', k: 'monkey' },
            { e: '🐒', n: 'monkey', k: 'animal' },
            { e: '🐔', n: 'chicken', k: 'bird' },
            { e: '🐧', n: 'penguin', k: 'bird' },
            { e: '🐦', n: 'bird', k: 'animal' },
            { e: '🐤', n: 'baby chick', k: 'bird' },
            { e: '🦆', n: 'duck', k: 'bird' },
            { e: '🦅', n: 'eagle', k: 'bird' },
            { e: '🦉', n: 'owl', k: 'bird' },
            { e: '🦇', n: 'bat', k: 'animal' },
            { e: '🐺', n: 'wolf', k: 'animal' },
            { e: '🐗', n: 'boar', k: 'animal' },
            { e: '🐴', n: 'horse', k: 'animal' },
            { e: '🦄', n: 'unicorn', k: 'magic' },
            { e: '🐝', n: 'bee', k: 'insect' },
            { e: '🐛', n: 'bug', k: 'insect' },
            { e: '🦋', n: 'butterfly', k: 'insect' },
            { e: '🐌', n: 'snail', k: 'slow' },
            { e: '🐞', n: 'lady beetle', k: 'bug' },
            { e: '🐜', n: 'ant', k: 'insect' },
            { e: '🦟', n: 'mosquito', k: 'insect' },
            { e: '🦗', n: 'cricket', k: 'insect' },
            { e: '🕷️', n: 'spider', k: 'insect' },
            { e: '🦂', n: 'scorpion', k: 'insect' },
            { e: '🐢', n: 'turtle', k: 'slow' },
            { e: '🐍', n: 'snake', k: 'animal' },
            { e: '🦎', n: 'lizard', k: 'animal' },
            { e: '🦖', n: 't-rex', k: 'dinosaur' },
            { e: '🦕', n: 'sauropod', k: 'dinosaur' },
            { e: '🐙', n: 'octopus', k: 'sea' },
            { e: '🦑', n: 'squid', k: 'sea' },
            { e: '🦐', n: 'shrimp', k: 'sea' },
            { e: '🦞', n: 'lobster', k: 'sea' },
            { e: '🦀', n: 'crab', k: 'sea' },
            { e: '🐡', n: 'blowfish', k: 'fish' },
            { e: '🐠', n: 'tropical fish', k: 'fish' },
            { e: '🐟', n: 'fish', k: 'sea' },
            { e: '🐬', n: 'dolphin', k: 'sea' },
            { e: '🐳', n: 'whale', k: 'sea' },
            { e: '🐋', n: 'whale', k: 'sea' },
            { e: '🦈', n: 'shark', k: 'sea' },
            { e: '🐊', n: 'crocodile', k: 'animal' },
            { e: '🐅', n: 'tiger', k: 'animal' },
            { e: '🐆', n: 'leopard', k: 'animal' },
            { e: '🦓', n: 'zebra', k: 'animal' },
            { e: '🦍', n: 'gorilla', k: 'animal' },
            { e: '🦧', n: 'orangutan', k: 'animal' },
            { e: '🐘', n: 'elephant', k: 'animal' },
            { e: '🦛', n: 'hippo', k: 'animal' },
            { e: '🦏', n: 'rhino', k: 'animal' },
            { e: '🐪', n: 'camel', k: 'animal' },
            { e: '🦒', n: 'giraffe', k: 'animal' },
            { e: '🦘', n: 'kangaroo', k: 'animal' },
            { e: '🦬', n: 'bison', k: 'animal' },
            { e: '🐃', n: 'water buffalo', k: 'animal' },
            { e: '🐂', n: 'ox', k: 'animal' },
            { e: '🐄', n: 'cow', k: 'animal' },
            { e: '🐎', n: 'racehorse', k: 'animal' },
            { e: '🐖', n: 'pig', k: 'animal' },
            { e: '🐏', n: 'ram', k: 'animal' },
            { e: '🐑', n: 'sheep', k: 'animal' },
            { e: '🦙', n: 'llama', k: 'animal' },
            { e: '🐐', n: 'goat', k: 'animal' },
            { e: '🦌', n: 'deer', k: 'animal' },
            { e: '🐕', n: 'dog', k: 'pet' },
            { e: '🐩', n: 'poodle', k: 'dog' },
            { e: '🦮', n: 'guide dog', k: 'dog' },
            { e: '🐈', n: 'cat', k: 'pet' },
            { e: '🪶', n: 'feather', k: 'bird' },
            { e: '🐓', n: 'rooster', k: 'bird' },
            { e: '🦃', n: 'turkey', k: 'bird' },
            { e: '🦤', n: 'dodo', k: 'bird' },
            { e: '🦚', n: 'peacock', k: 'bird' },
            { e: '🦜', n: 'parrot', k: 'bird' },
            { e: '🦢', n: 'swan', k: 'bird' },
            { e: '🦩', n: 'flamingo', k: 'bird' },
            { e: '🕊️', n: 'dove', k: 'peace' },
            { e: '🐇', n: 'rabbit', k: 'bunny' },
            { e: '🦝', n: 'raccoon', k: 'animal' },
            { e: '🦨', n: 'skunk', k: 'animal' },
            { e: '🦡', n: 'badger', k: 'animal' },
            { e: '🦫', n: 'beaver', k: 'animal' },
            { e: '🦦', n: 'otter', k: 'animal' },
            { e: '🦥', n: 'sloth', k: 'slow' },
            { e: '🐁', n: 'mouse', k: 'rodent' },
            { e: '🐀', n: 'rat', k: 'rodent' },
            { e: '🐿️', n: 'chipmunk', k: 'animal' },
            { e: '🦔', n: 'hedgehog', k: 'animal' },
            { e: '🐾', n: 'paw prints', k: 'pet' },
            { e: '🐉', n: 'dragon', k: 'myth' },
            { e: '🐲', n: 'dragon face', k: 'myth' },
            { e: '🌵', n: 'cactus', k: 'plant' },
            { e: '🎄', n: 'christmas tree', k: 'holiday' },
            { e: '🌲', n: 'evergreen', k: 'tree' },
            { e: '🌳', n: 'deciduous', k: 'tree' },
            { e: '🌴', n: 'palm', k: 'tree' },
            { e: '🌱', n: 'seedling', k: 'plant' },
            { e: '🌿', n: 'herb', k: 'plant' },
            { e: '☘️', n: 'shamrock', k: 'luck' },
            { e: '🍀', n: 'four leaf clover', k: 'luck' },
            { e: '🎋', n: 'bamboo', k: 'plant' },
            { e: '🍃', n: 'leaves', k: 'wind' },
            { e: '🍂', n: 'fallen leaf', k: 'autumn' },
            { e: '🍁', n: 'maple leaf', k: 'autumn' },
            { e: '🍄', n: 'mushroom', k: 'fungus' },
            { e: '🐚', n: 'shell', k: 'sea' },
            { e: '🌾', n: 'sheaf of rice', k: 'plant' },
            { e: '💐', n: 'bouquet', k: 'flowers' },
            { e: '🌷', n: 'tulip', k: 'flower' },
            { e: '🌹', n: 'rose', k: 'flower' },
            { e: '🥀', n: 'wilted flower', k: 'sad' },
            { e: '🌺', n: 'hibiscus', k: 'flower' },
            { e: '🌸', n: 'cherry blossom', k: 'flower' },
            { e: '🌼', n: 'blossom', k: 'flower' },
            { e: '🌻', n: 'sunflower', k: 'flower' },
            { e: '🌞', n: 'sun face', k: 'weather' },
            { e: '🌝', n: 'full moon face', k: 'night' },
            { e: '🌛', n: 'first quarter moon', k: 'night' },
            { e: '🌜', n: 'last quarter moon', k: 'night' },
            { e: '🌚', n: 'new moon face', k: 'night' },
            { e: '🌕', n: 'full moon', k: 'night' },
            { e: '🌖', n: 'waning gibbous', k: 'night' },
            { e: '🌗', n: 'last quarter', k: 'night' },
            { e: '🌘', n: 'waning crescent', k: 'night' },
            { e: '🌑', n: 'new moon', k: 'night' },
            { e: '🌒', n: 'waxing crescent', k: 'night' },
            { e: '🌓', n: 'first quarter', k: 'night' },
            { e: '🌔', n: 'waxing gibbous', k: 'night' },
            { e: '🌙', n: 'crescent moon', k: 'night' },
            { e: '🌎', n: 'earth americas', k: 'world' },
            { e: '🌍', n: 'earth africa', k: 'world' },
            { e: '🌏', n: 'earth asia', k: 'world' },
            { e: '🪐', n: 'ringed planet', k: 'space' },
            { e: '💫', n: 'dizzy', k: 'star' },
            { e: '⭐', n: 'star', k: 'night' },
            { e: '🌟', n: 'glowing star', k: 'night' },
            { e: '✨', n: 'sparkles', k: 'magic' },
            { e: '⚡', n: 'zap', k: 'lightning' },
            { e: '☄️', n: 'comet', k: 'space' },
            { e: '💥', n: 'boom', k: 'explosion' },
            { e: '🔥', n: 'fire', k: 'hot lit' },
            { e: '🌪️', n: 'tornado', k: 'weather' },
            { e: '🌈', n: 'rainbow', k: 'weather' },
            { e: '☀️', n: 'sun', k: 'weather' },
            { e: '🌤️', n: 'sun behind cloud', k: 'weather' },
            { e: '⛅', n: 'partly sunny', k: 'weather' },
            { e: '☁️', n: 'cloud', k: 'weather' },
            { e: '🌧️', n: 'cloud rain', k: 'weather' },
            { e: '⛈️', n: 'cloud lightning', k: 'weather' },
            { e: '🌩️', n: 'cloud lightning', k: 'weather' },
            { e: '🌨️', n: 'cloud snow', k: 'weather' },
            { e: '❄️', n: 'snowflake', k: 'cold' },
            { e: '☃️', n: 'snowman', k: 'winter' },
            { e: '⛄', n: 'snowman without snow', k: 'winter' },
            { e: '💨', n: 'dash', k: 'wind' },
            { e: '💧', n: 'droplet', k: 'water' },
            { e: '💦', n: 'sweat droplets', k: 'water' },
            { e: '☔', n: 'umbrella rain', k: 'weather' },
            { e: '☂️', n: 'umbrella', k: 'weather' },
            { e: '🌊', n: 'ocean', k: 'wave' },
            { e: '🌫️', n: 'fog', k: 'weather' },
        ],
    },
    {
        id: 'food',
        label: 'Food',
        icon: '🍕',
        emojis: [
            { e: '🍏', n: 'green apple', k: 'fruit' },
            { e: '🍎', n: 'red apple', k: 'fruit' },
            { e: '🍐', n: 'pear', k: 'fruit' },
            { e: '🍊', n: 'tangerine', k: 'fruit' },
            { e: '🍋', n: 'lemon', k: 'fruit' },
            { e: '🍌', n: 'banana', k: 'fruit' },
            { e: '🍉', n: 'watermelon', k: 'fruit' },
            { e: '🍇', n: 'grapes', k: 'fruit' },
            { e: '🍓', n: 'strawberry', k: 'fruit' },
            { e: '🫐', n: 'blueberries', k: 'fruit' },
            { e: '🍈', n: 'melon', k: 'fruit' },
            { e: '🍒', n: 'cherries', k: 'fruit' },
            { e: '🍑', n: 'peach', k: 'fruit' },
            { e: '🥭', n: 'mango', k: 'fruit' },
            { e: '🍍', n: 'pineapple', k: 'fruit' },
            { e: '🥥', n: 'coconut', k: 'fruit' },
            { e: '🥝', n: 'kiwi', k: 'fruit' },
            { e: '🍅', n: 'tomato', k: 'veggie' },
            { e: '🍆', n: 'eggplant', k: 'veggie' },
            { e: '🥑', n: 'avocado', k: 'veggie' },
            { e: '🥦', n: 'broccoli', k: 'veggie' },
            { e: '🥬', n: 'leafy green', k: 'veggie' },
            { e: '🥒', n: 'cucumber', k: 'veggie' },
            { e: '🌶️', n: 'hot pepper', k: 'spicy' },
            { e: '🫑', n: 'bell pepper', k: 'veggie' },
            { e: '🌽', n: 'corn', k: 'veggie' },
            { e: '🥕', n: 'carrot', k: 'veggie' },
            { e: '🫒', n: 'olive', k: 'veggie' },
            { e: '🧄', n: 'garlic', k: 'veggie' },
            { e: '🧅', n: 'onion', k: 'veggie' },
            { e: '🥔', n: 'potato', k: 'veggie' },
            { e: '🍠', n: 'sweet potato', k: 'veggie' },
            { e: '🥐', n: 'croissant', k: 'bread' },
            { e: '🥯', n: 'bagel', k: 'bread' },
            { e: '🍞', n: 'bread', k: 'food' },
            { e: '🥖', n: 'baguette', k: 'bread' },
            { e: '🥨', n: 'pretzel', k: 'bread' },
            { e: '🧀', n: 'cheese', k: 'food' },
            { e: '🥚', n: 'egg', k: 'food' },
            { e: '🍳', n: 'cooking', k: 'egg' },
            { e: '🧈', n: 'butter', k: 'food' },
            { e: '🥞', n: 'pancakes', k: 'breakfast' },
            { e: '🧇', n: 'waffle', k: 'breakfast' },
            { e: '🥓', n: 'bacon', k: 'meat' },
            { e: '🥩', n: 'cut of meat', k: 'steak' },
            { e: '🍗', n: 'poultry leg', k: 'chicken' },
            { e: '🍖', n: 'meat on bone', k: 'food' },
            { e: '🦴', n: 'bone', k: 'food' },
            { e: '🌭', n: 'hot dog', k: 'food' },
            { e: '🍔', n: 'hamburger', k: 'burger' },
            { e: '🍟', n: 'fries', k: 'food' },
            { e: '🍕', n: 'pizza', k: 'food' },
            { e: '🫓', n: 'flatbread', k: 'food' },
            { e: '🥪', n: 'sandwich', k: 'food' },
            { e: '🥙', n: 'stuffed flatbread', k: 'food' },
            { e: '🧆', n: 'falafel', k: 'food' },
            { e: '🌮', n: 'taco', k: 'food' },
            { e: '🌯', n: 'burrito', k: 'food' },
            { e: '🫔', n: 'tamale', k: 'food' },
            { e: '🥗', n: 'green salad', k: 'healthy' },
            { e: '🥘', n: 'shallow pan', k: 'paella' },
            { e: '🫕', n: 'fondue', k: 'food' },
            { e: '🥫', n: 'canned food', k: 'food' },
            { e: '🍝', n: 'spaghetti', k: 'pasta' },
            { e: '🍜', n: 'ramen', k: 'noodles' },
            { e: '🍲', n: 'stew', k: 'food' },
            { e: '🍛', n: 'curry', k: 'food' },
            { e: '🍣', n: 'sushi', k: 'food' },
            { e: '🍱', n: 'bento', k: 'food' },
            { e: '🥟', n: 'dumpling', k: 'food' },
            { e: '🦪', n: 'oyster', k: 'seafood' },
            { e: '🍤', n: 'fried shrimp', k: 'seafood' },
            { e: '🍙', n: 'rice ball', k: 'food' },
            { e: '🍚', n: 'cooked rice', k: 'food' },
            { e: '🍘', n: 'rice cracker', k: 'food' },
            { e: '🍥', n: 'fish cake', k: 'food' },
            { e: '🥠', n: 'fortune cookie', k: 'food' },
            { e: '🥮', n: 'moon cake', k: 'food' },
            { e: '🍢', n: 'oden', k: 'food' },
            { e: '🍡', n: 'dango', k: 'food' },
            { e: '🍧', n: 'shaved ice', k: 'dessert' },
            { e: '🍨', n: 'ice cream', k: 'dessert' },
            { e: '🍦', n: 'soft ice cream', k: 'dessert' },
            { e: '🥧', n: 'pie', k: 'dessert' },
            { e: '🧁', n: 'cupcake', k: 'dessert' },
            { e: '🍰', n: 'cake', k: 'dessert' },
            { e: '🎂', n: 'birthday', k: 'cake' },
            { e: '🍮', n: 'custard', k: 'dessert' },
            { e: '🍭', n: 'lollipop', k: 'candy' },
            { e: '🍬', n: 'candy', k: 'sweet' },
            { e: '🍫', n: 'chocolate', k: 'sweet' },
            { e: '🍿', n: 'popcorn', k: 'snack' },
            { e: '🍩', n: 'doughnut', k: 'dessert' },
            { e: '🍪', n: 'cookie', k: 'dessert' },
            { e: '🌰', n: 'chestnut', k: 'nut' },
            { e: '🥜', n: 'peanuts', k: 'nut' },
            { e: '🍯', n: 'honey', k: 'sweet' },
            { e: '🥛', n: 'milk', k: 'drink' },
            { e: '🍼', n: 'baby bottle', k: 'drink' },
            { e: '☕', n: 'coffee', k: 'drink' },
            { e: '🫖', n: 'teapot', k: 'drink' },
            { e: '🍵', n: 'tea', k: 'drink' },
            { e: '🧃', n: 'juice box', k: 'drink' },
            { e: '🥤', n: 'cup with straw', k: 'drink' },
            { e: '🧋', n: 'bubble tea', k: 'drink' },
            { e: '🍶', n: 'sake', k: 'drink' },
            { e: '🍺', n: 'beer', k: 'drink' },
            { e: '🍻', n: 'beers', k: 'cheers' },
            { e: '🥂', n: 'clinking glasses', k: 'cheers' },
            { e: '🍷', n: 'wine', k: 'drink' },
            { e: '🥃', n: 'tumbler', k: 'whisky' },
            { e: '🍸', n: 'cocktail', k: 'drink' },
            { e: '🍹', n: 'tropical drink', k: 'drink' },
            { e: '🧉', n: 'mate', k: 'drink' },
            { e: '🍾', n: 'champagne', k: 'celebrate' },
            { e: '🧊', n: 'ice', k: 'cold' },
            { e: '🥄', n: 'spoon', k: 'utensil' },
            { e: '🍴', n: 'fork and knife', k: 'utensil' },
            { e: '🍽️', n: 'plate', k: 'dining' },
            { e: '🥣', n: 'bowl spoon', k: 'cereal' },
            { e: '🥡', n: 'takeout', k: 'food' },
            { e: '🥢', n: 'chopsticks', k: 'utensil' },
            { e: '🧂', n: 'salt', k: 'seasoning' },
        ],
    },
    {
        id: 'activity',
        label: 'Activity',
        icon: '⚽',
        emojis: [
            { e: '⚽', n: 'soccer', k: 'football sport' },
            { e: '🏀', n: 'basketball', k: 'sport' },
            { e: '🏈', n: 'american football', k: 'sport' },
            { e: '⚾', n: 'baseball', k: 'sport' },
            { e: '🥎', n: 'softball', k: 'sport' },
            { e: '🎾', n: 'tennis', k: 'sport' },
            { e: '🏐', n: 'volleyball', k: 'sport' },
            { e: '🏉', n: 'rugby', k: 'sport' },
            { e: '🥏', n: 'flying disc', k: 'frisbee' },
            { e: '🎱', n: '8ball', k: 'pool' },
            { e: '🪀', n: 'yo-yo', k: 'toy' },
            { e: '🏓', n: 'ping pong', k: 'sport' },
            { e: '🏸', n: 'badminton', k: 'sport' },
            { e: '🏒', n: 'ice hockey', k: 'sport' },
            { e: '🏑', n: 'field hockey', k: 'sport' },
            { e: '🥍', n: 'lacrosse', k: 'sport' },
            { e: '🏏', n: 'cricket', k: 'sport' },
            { e: '🪃', n: 'boomerang', k: 'sport' },
            { e: '🥅', n: 'goal net', k: 'sport' },
            { e: '⛳', n: 'golf', k: 'sport' },
            { e: '🪁', n: 'kite', k: 'fly' },
            { e: '🏹', n: 'bow and arrow', k: 'archery' },
            { e: '🎣', n: 'fishing', k: 'sport' },
            { e: '🤿', n: 'diving mask', k: 'swim' },
            { e: '🥊', n: 'boxing', k: 'sport' },
            { e: '🥋', n: 'martial arts', k: 'sport' },
            { e: '🎽', n: 'running shirt', k: 'sport' },
            { e: '🛹', n: 'skateboard', k: 'sport' },
            { e: '🛼', n: 'roller skate', k: 'sport' },
            { e: '🛷', n: 'sled', k: 'winter' },
            { e: '⛸️', n: 'ice skate', k: 'winter' },
            { e: '🥌', n: 'curling', k: 'sport' },
            { e: '🎿', n: 'ski', k: 'winter' },
            { e: '⛷️', n: 'skier', k: 'winter' },
            { e: '🏂', n: 'snowboarder', k: 'winter' },
            { e: '🪂', n: 'parachute', k: 'sky' },
            { e: '🏋️', n: 'weight lifting', k: 'gym' },
            { e: '🤼', n: 'wrestling', k: 'sport' },
            { e: '🤸', n: 'cartwheel', k: 'gym' },
            { e: '⛹️', n: 'bouncing ball', k: 'sport' },
            { e: '🤺', n: 'fencing', k: 'sport' },
            { e: '🤾', n: 'handball', k: 'sport' },
            { e: '🏌️', n: 'golfing', k: 'sport' },
            { e: '🏇', n: 'horse racing', k: 'sport' },
            { e: '🧘', n: 'lotus', k: 'yoga' },
            { e: '🏄', n: 'surfing', k: 'sport' },
            { e: '🏊', n: 'swimming', k: 'sport' },
            { e: '🤽', n: 'water polo', k: 'sport' },
            { e: '🚣', n: 'rowboat', k: 'sport' },
            { e: '🧗', n: 'climbing', k: 'sport' },
            { e: '🚵', n: 'mountain biking', k: 'sport' },
            { e: '🚴', n: 'biking', k: 'sport' },
            { e: '🏆', n: 'trophy', k: 'win' },
            { e: '🥇', n: 'gold medal', k: 'first' },
            { e: '🥈', n: 'silver medal', k: 'second' },
            { e: '🥉', n: 'bronze medal', k: 'third' },
            { e: '🏅', n: 'sports medal', k: 'win' },
            { e: '🎖️', n: 'military medal', k: 'win' },
            { e: '🏵️', n: 'rosette', k: 'award' },
            { e: '🎗️', n: 'reminder ribbon', k: 'awareness' },
            { e: '🎫', n: 'ticket', k: 'event' },
            { e: '🎟️', n: 'tickets', k: 'event' },
            { e: '🎪', n: 'circus', k: 'tent' },
            { e: '🤹', n: 'juggling', k: 'circus' },
            { e: '🎭', n: 'performing arts', k: 'theater' },
            { e: '🩰', n: 'ballet', k: 'dance' },
            { e: '🎨', n: 'art', k: 'paint' },
            { e: '🎬', n: 'clapper', k: 'movie' },
            { e: '🎤', n: 'microphone', k: 'sing' },
            { e: '🎧', n: 'headphones', k: 'music' },
            { e: '🎼', n: 'musical score', k: 'music' },
            { e: '🎹', n: 'piano', k: 'music' },
            { e: '🥁', n: 'drum', k: 'music' },
            { e: '🪘', n: 'long drum', k: 'music' },
            { e: '🎷', n: 'saxophone', k: 'music' },
            { e: '🎺', n: 'trumpet', k: 'music' },
            { e: '🎸', n: 'guitar', k: 'music' },
            { e: '🪕', n: 'banjo', k: 'music' },
            { e: '🎻', n: 'violin', k: 'music' },
            { e: '🎲', n: 'dice', k: 'game' },
            { e: '♟️', n: 'chess', k: 'game' },
            { e: '🎯', n: 'direct hit', k: 'bullseye' },
            { e: '🎳', n: 'bowling', k: 'sport' },
            { e: '🎮', n: 'video game', k: 'controller' },
            { e: '🎰', n: 'slot machine', k: 'casino' },
            { e: '🧩', n: 'puzzle', k: 'jigsaw' },
        ],
    },
    {
        id: 'objects',
        label: 'Objects',
        icon: '💡',
        emojis: [
            { e: '⌚', n: 'watch', k: 'time' },
            { e: '📱', n: 'mobile phone', k: 'iphone' },
            { e: '📲', n: 'mobile arrow', k: 'call' },
            { e: '💻', n: 'laptop', k: 'computer' },
            { e: '⌨️', n: 'keyboard', k: 'computer' },
            { e: '🖥️', n: 'desktop', k: 'computer' },
            { e: '🖨️', n: 'printer', k: 'computer' },
            { e: '🖱️', n: 'mouse', k: 'computer' },
            { e: '🖲️', n: 'trackball', k: 'computer' },
            { e: '🕹️', n: 'joystick', k: 'game' },
            { e: '🗜️', n: 'clamp', k: 'tool' },
            { e: '💽', n: 'minidisc', k: 'disk' },
            { e: '💾', n: 'floppy', k: 'save' },
            { e: '💿', n: 'cd', k: 'disk' },
            { e: '📀', n: 'dvd', k: 'disk' },
            { e: '📼', n: 'vhs', k: 'tape' },
            { e: '📷', n: 'camera', k: 'photo' },
            { e: '📸', n: 'camera flash', k: 'photo' },
            { e: '📹', n: 'video camera', k: 'film' },
            { e: '🎥', n: 'movie camera', k: 'film' },
            { e: '📽️', n: 'film projector', k: 'movie' },
            { e: '🎞️', n: 'film frames', k: 'movie' },
            { e: '📞', n: 'telephone receiver', k: 'call' },
            { e: '☎️', n: 'telephone', k: 'call' },
            { e: '📟', n: 'pager', k: 'call' },
            { e: '📠', n: 'fax', k: 'office' },
            { e: '📺', n: 'tv', k: 'television' },
            { e: '📻', n: 'radio', k: 'music' },
            { e: '🧭', n: 'compass', k: 'navigate' },
            { e: '⏱️', n: 'stopwatch', k: 'time' },
            { e: '⏲️', n: 'timer', k: 'time' },
            { e: '⏰', n: 'alarm', k: 'time' },
            { e: '🕰️', n: 'mantelpiece clock', k: 'time' },
            { e: '⌛', n: 'hourglass', k: 'time' },
            { e: '⏳', n: 'hourglass flowing', k: 'wait' },
            { e: '📡', n: 'satellite', k: 'signal' },
            { e: '🔋', n: 'battery', k: 'power' },
            { e: '🔌', n: 'electric plug', k: 'power' },
            { e: '💡', n: 'bulb', k: 'idea light' },
            { e: '🔦', n: 'flashlight', k: 'light' },
            { e: '🕯️', n: 'candle', k: 'light' },
            { e: '🪔', n: 'diya lamp', k: 'light' },
            { e: '🧯', n: 'fire extinguisher', k: 'safety' },
            { e: '🛢️', n: 'oil drum', k: 'fuel' },
            { e: '💸', n: 'money with wings', k: 'cash' },
            { e: '💵', n: 'dollar', k: 'money' },
            { e: '💴', n: 'yen', k: 'money' },
            { e: '💶', n: 'euro', k: 'money' },
            { e: '💷', n: 'pound', k: 'money' },
            { e: '🪙', n: 'coin', k: 'money' },
            { e: '💰', n: 'money bag', k: 'rich' },
            { e: '💳', n: 'credit card', k: 'pay' },
            { e: '💎', n: 'gem', k: 'diamond' },
            { e: '⚖️', n: 'balance scale', k: 'justice' },
            { e: '🪜', n: 'ladder', k: 'tool' },
            { e: '🧰', n: 'toolbox', k: 'tool' },
            { e: '🪛', n: 'screwdriver', k: 'tool' },
            { e: '🔧', n: 'wrench', k: 'tool' },
            { e: '🔨', n: 'hammer', k: 'tool' },
            { e: '⚒️', n: 'hammer and pick', k: 'tool' },
            { e: '🛠️', n: 'hammer and wrench', k: 'tool' },
            { e: '⛏️', n: 'pick', k: 'tool' },
            { e: '🪚', n: 'saw', k: 'tool' },
            { e: '🔩', n: 'nut and bolt', k: 'tool' },
            { e: '⚙️', n: 'gear', k: 'settings' },
            { e: '🪤', n: 'mouse trap', k: 'trap' },
            { e: '🧱', n: 'brick', k: 'build' },
            { e: '⛓️', n: 'chains', k: 'link' },
            { e: '🧲', n: 'magnet', k: 'attract' },
            { e: '🔫', n: 'pistol', k: 'gun' },
            { e: '💣', n: 'bomb', k: 'explode' },
            { e: '🧨', n: 'firecracker', k: 'boom' },
            { e: '🪓', n: 'axe', k: 'tool' },
            { e: '🔪', n: 'kitchen knife', k: 'cut' },
            { e: '🗡️', n: 'dagger', k: 'weapon' },
            { e: '⚔️', n: 'crossed swords', k: 'fight' },
            { e: '🛡️', n: 'shield', k: 'protect' },
            { e: '🚬', n: 'cigarette', k: 'smoke' },
            { e: '⚰️', n: 'coffin', k: 'death' },
            { e: '🪦', n: 'headstone', k: 'death' },
            { e: '⚱️', n: 'funeral urn', k: 'death' },
            { e: '🏺', n: 'amphora', k: 'vase' },
            { e: '🔮', n: 'crystal ball', k: 'magic' },
            { e: '📿', n: 'prayer beads', k: 'religion' },
            { e: '🧿', n: 'nazar', k: 'amulet' },
            { e: '💈', n: 'barber', k: 'pole' },
            { e: '⚗️', n: 'alembic', k: 'science' },
            { e: '🔭', n: 'telescope', k: 'science' },
            { e: '🔬', n: 'microscope', k: 'science' },
            { e: '🕳️', n: 'hole', k: 'empty' },
            { e: '🩹', n: 'adhesive bandage', k: 'heal' },
            { e: '🩺', n: 'stethoscope', k: 'doctor' },
            { e: '💊', n: 'pill', k: 'medicine' },
            { e: '💉', n: 'syringe', k: 'medicine' },
            { e: '🩸', n: 'drop of blood', k: 'blood' },
            { e: '🧬', n: 'dna', k: 'science' },
            { e: '🦠', n: 'microbe', k: 'virus' },
            { e: '🧫', n: 'petri dish', k: 'science' },
            { e: '🧪', n: 'test tube', k: 'science' },
            { e: '🌡️', n: 'thermometer', k: 'temp' },
            { e: '🧹', n: 'broom', k: 'clean' },
            { e: '🪠', n: 'plunger', k: 'clean' },
            { e: '🧺', n: 'basket', k: 'laundry' },
            { e: '🧻', n: 'toilet paper', k: 'bathroom' },
            { e: '🚽', n: 'toilet', k: 'bathroom' },
            { e: '🚰', n: 'potable water', k: 'drink' },
            { e: '🚿', n: 'shower', k: 'bath' },
            { e: '🛁', n: 'bathtub', k: 'bath' },
            { e: '🛀', n: 'bathing', k: 'bath' },
            { e: '🧼', n: 'soap', k: 'clean' },
            { e: '🪥', n: 'toothbrush', k: 'clean' },
            { e: '🪒', n: 'razor', k: 'shave' },
            { e: '🧽', n: 'sponge', k: 'clean' },
            { e: '🪣', n: 'bucket', k: 'clean' },
            { e: '🧴', n: 'lotion', k: 'bottle' },
            { e: '🛎️', n: 'bellhop', k: 'hotel' },
            { e: '🔑', n: 'key', k: 'lock' },
            { e: '🗝️', n: 'old key', k: 'lock' },
            { e: '🚪', n: 'door', k: 'enter' },
            { e: '🪑', n: 'chair', k: 'sit' },
            { e: '🛋️', n: 'couch', k: 'sofa' },
            { e: '🛏️', n: 'bed', k: 'sleep' },
            { e: '🛌', n: 'sleeping bed', k: 'sleep' },
            { e: '🧸', n: 'teddy bear', k: 'toy' },
            { e: '🖼️', n: 'framed picture', k: 'art' },
            { e: '🛍️', n: 'shopping bags', k: 'buy' },
            { e: '🛒', n: 'shopping cart', k: 'buy' },
            { e: '🎁', n: 'gift', k: 'present' },
            { e: '🎈', n: 'balloon', k: 'party' },
            { e: '🎏', n: 'carp streamer', k: 'flag' },
            { e: '🎀', n: 'ribbon', k: 'bow' },
            { e: '🪄', n: 'magic wand', k: 'magic' },
            { e: '🪅', n: 'pinata', k: 'party' },
            { e: '🎊', n: 'confetti ball', k: 'party' },
            { e: '🎉', n: 'tada', k: 'party celebrate' },
            { e: '🎎', n: 'dolls', k: 'japan' },
            { e: '🏮', n: 'red paper lantern', k: 'light' },
            { e: '🎐', n: 'wind chime', k: 'japan' },
            { e: '🧧', n: 'red envelope', k: 'gift' },
            { e: '✉️', n: 'envelope', k: 'mail' },
            { e: '📩', n: 'envelope arrow', k: 'mail' },
            { e: '📨', n: 'incoming envelope', k: 'mail' },
            { e: '📧', n: 'e-mail', k: 'mail' },
            { e: '💌', n: 'love letter', k: 'mail' },
            { e: '📥', n: 'inbox', k: 'mail' },
            { e: '📤', n: 'outbox', k: 'mail' },
            { e: '📦', n: 'package', k: 'box' },
            { e: '🏷️', n: 'label', k: 'tag' },
            { e: '🪧', n: 'placard', k: 'sign' },
            { e: '📪', n: 'mailbox closed', k: 'mail' },
            { e: '📫', n: 'mailbox', k: 'mail' },
            { e: '📬', n: 'mailbox with mail', k: 'mail' },
            { e: '📭', n: 'mailbox no mail', k: 'mail' },
            { e: '📮', n: 'postbox', k: 'mail' },
            { e: '📯', n: 'postal horn', k: 'mail' },
            { e: '📜', n: 'scroll', k: 'document' },
            { e: '📃', n: 'page curl', k: 'document' },
            { e: '📄', n: 'page facing up', k: 'document' },
            { e: '📑', n: 'bookmark tabs', k: 'document' },
            { e: '🧾', n: 'receipt', k: 'bill' },
            { e: '📊', n: 'bar chart', k: 'stats' },
            { e: '📈', n: 'chart up', k: 'growth' },
            { e: '📉', n: 'chart down', k: 'loss' },
            { e: '🗒️', n: 'spiral notepad', k: 'notes' },
            { e: '🗓️', n: 'spiral calendar', k: 'date' },
            { e: '📆', n: 'tear-off calendar', k: 'date' },
            { e: '📅', n: 'calendar', k: 'date' },
            { e: '🗑️', n: 'wastebasket', k: 'trash' },
            { e: '📇', n: 'card index', k: 'office' },
            { e: '🗃️', n: 'card file box', k: 'office' },
            { e: '🗳️', n: 'ballot box', k: 'vote' },
            { e: '🗄️', n: 'file cabinet', k: 'office' },
            { e: '📋', n: 'clipboard', k: 'office' },
            { e: '📁', n: 'file folder', k: 'office' },
            { e: '📂', n: 'open file folder', k: 'office' },
            { e: '🗂️', n: 'card index dividers', k: 'office' },
            { e: '🗞️', n: 'rolled newspaper', k: 'news' },
            { e: '📰', n: 'newspaper', k: 'news' },
            { e: '📓', n: 'notebook', k: 'notes' },
            { e: '📔', n: 'notebook decorative', k: 'notes' },
            { e: '📒', n: 'ledger', k: 'notes' },
            { e: '📕', n: 'closed book', k: 'read' },
            { e: '📗', n: 'green book', k: 'read' },
            { e: '📘', n: 'blue book', k: 'read' },
            { e: '📙', n: 'orange book', k: 'read' },
            { e: '📚', n: 'books', k: 'read' },
            { e: '📖', n: 'open book', k: 'read' },
            { e: '🔖', n: 'bookmark', k: 'save' },
            { e: '🧷', n: 'safety pin', k: 'pin' },
            { e: '🔗', n: 'link', k: 'url' },
            { e: '📎', n: 'paperclip', k: 'attach' },
            { e: '🖇️', n: 'linked paperclips', k: 'attach' },
            { e: '📐', n: 'triangular ruler', k: 'measure' },
            { e: '📏', n: 'straight ruler', k: 'measure' },
            { e: '🧮', n: 'abacus', k: 'math' },
            { e: '📌', n: 'pushpin', k: 'pin' },
            { e: '📍', n: 'round pushpin', k: 'location' },
            { e: '✂️', n: 'scissors', k: 'cut' },
            { e: '🖊️', n: 'pen', k: 'write' },
            { e: '🖋️', n: 'fountain pen', k: 'write' },
            { e: '✒️', n: 'black nib', k: 'write' },
            { e: '🖌️', n: 'paintbrush', k: 'art' },
            { e: '🖍️', n: 'crayon', k: 'art' },
            { e: '📝', n: 'memo', k: 'note' },
            { e: '✏️', n: 'pencil', k: 'write' },
            { e: '🔍', n: 'magnifying glass left', k: 'search' },
            { e: '🔎', n: 'magnifying glass right', k: 'search' },
            { e: '🔏', n: 'lock with pen', k: 'secure' },
            { e: '🔐', n: 'locked with key', k: 'secure' },
            { e: '🔒', n: 'locked', k: 'secure' },
            { e: '🔓', n: 'unlocked', k: 'open' },
        ],
    },
    {
        id: 'symbols',
        label: 'Symbols',
        icon: '✅',
        emojis: [
            { e: '❤️', n: 'red heart', k: 'love' },
            { e: '🧡', n: 'orange heart', k: 'love' },
            { e: '💛', n: 'yellow heart', k: 'love' },
            { e: '💚', n: 'green heart', k: 'love' },
            { e: '💙', n: 'blue heart', k: 'love' },
            { e: '💜', n: 'purple heart', k: 'love' },
            { e: '🖤', n: 'black heart', k: 'love' },
            { e: '🤍', n: 'white heart', k: 'love' },
            { e: '🤎', n: 'brown heart', k: 'love' },
            { e: '💔', n: 'broken heart', k: 'sad' },
            { e: '❣️', n: 'heart exclamation', k: 'love' },
            { e: '💕', n: 'two hearts', k: 'love' },
            { e: '💞', n: 'revolving hearts', k: 'love' },
            { e: '💓', n: 'beating heart', k: 'love' },
            { e: '💗', n: 'growing heart', k: 'love' },
            { e: '💖', n: 'sparkling heart', k: 'love' },
            { e: '💘', n: 'cupid', k: 'love' },
            { e: '💝', n: 'gift heart', k: 'love' },
            { e: '💟', n: 'heart decoration', k: 'love' },
            { e: '☮️', n: 'peace', k: 'symbol' },
            { e: '✝️', n: 'cross', k: 'religion' },
            { e: '☪️', n: 'star and crescent', k: 'religion' },
            { e: '🕉️', n: 'om', k: 'religion' },
            { e: '☸️', n: 'wheel of dharma', k: 'religion' },
            { e: '✡️', n: 'star of david', k: 'religion' },
            { e: '🔯', n: 'dotted six-pointed star', k: 'religion' },
            { e: '🕎', n: 'menorah', k: 'religion' },
            { e: '☯️', n: 'yin yang', k: 'balance' },
            { e: '☦️', n: 'orthodox cross', k: 'religion' },
            { e: '🛐', n: 'place of worship', k: 'religion' },
            { e: '⛎', n: 'ophiuchus', k: 'zodiac' },
            { e: '♈', n: 'aries', k: 'zodiac' },
            { e: '♉', n: 'taurus', k: 'zodiac' },
            { e: '♊', n: 'gemini', k: 'zodiac' },
            { e: '♋', n: 'cancer', k: 'zodiac' },
            { e: '♌', n: 'leo', k: 'zodiac' },
            { e: '♍', n: 'virgo', k: 'zodiac' },
            { e: '♎', n: 'libra', k: 'zodiac' },
            { e: '♏', n: 'scorpio', k: 'zodiac' },
            { e: '♐', n: 'sagittarius', k: 'zodiac' },
            { e: '♑', n: 'capricorn', k: 'zodiac' },
            { e: '♒', n: 'aquarius', k: 'zodiac' },
            { e: '♓', n: 'pisces', k: 'zodiac' },
            { e: '🆔', n: 'id', k: 'button' },
            { e: '⚛️', n: 'atom', k: 'science' },
            { e: '🉑', n: 'accept', k: 'japanese' },
            { e: '☢️', n: 'radioactive', k: 'danger' },
            { e: '☣️', n: 'biohazard', k: 'danger' },
            { e: '📴', n: 'mobile off', k: 'phone' },
            { e: '📳', n: 'vibration', k: 'phone' },
            { e: '🈶', n: 'not free of charge', k: 'japanese' },
            { e: '🈚', n: 'free of charge', k: 'japanese' },
            { e: '🈸', n: 'application', k: 'japanese' },
            { e: '🈺', n: 'open for business', k: 'japanese' },
            { e: '🈷️', n: 'monthly amount', k: 'japanese' },
            { e: '✴️', n: 'eight pointed star', k: 'symbol' },
            { e: '🆚', n: 'vs', k: 'versus' },
            { e: '💮', n: 'white flower', k: 'symbol' },
            { e: '🉐', n: 'bargain', k: 'japanese' },
            { e: '㊙️', n: 'secret', k: 'japanese' },
            { e: '㊗️', n: 'congratulations', k: 'japanese' },
            { e: '🈴', n: 'passing grade', k: 'japanese' },
            { e: '🈵', n: 'no vacancy', k: 'japanese' },
            { e: '🈹', n: 'discount', k: 'japanese' },
            { e: '🈲', n: 'prohibited', k: 'japanese' },
            { e: '🅰️', n: 'a button', k: 'blood' },
            { e: '🅱️', n: 'b button', k: 'blood' },
            { e: '🆎', n: 'ab button', k: 'blood' },
            { e: '🆑', n: 'cl', k: 'button' },
            { e: '🅾️', n: 'o button', k: 'blood' },
            { e: '🆘', n: 'sos', k: 'help' },
            { e: '❌', n: 'x', k: 'no cross' },
            { e: '⭕', n: 'o', k: 'circle' },
            { e: '🛑', n: 'stop', k: 'sign' },
            { e: '⛔', n: 'no entry', k: 'stop' },
            { e: '📛', n: 'name badge', k: 'badge' },
            { e: '🚫', n: 'prohibited', k: 'ban' },
            { e: '💯', n: 'hundred', k: 'perfect' },
            { e: '💢', n: 'anger', k: 'mad' },
            { e: '♨️', n: 'hotsprings', k: 'steam' },
            { e: '🚷', n: 'no pedestrians', k: 'ban' },
            { e: '🚯', n: 'no littering', k: 'ban' },
            { e: '🚳', n: 'no bicycles', k: 'ban' },
            { e: '🚱', n: 'non-potable water', k: 'ban' },
            { e: '🔞', n: 'no one under eighteen', k: 'ban' },
            { e: '📵', n: 'no mobile phones', k: 'ban' },
            { e: '🚭', n: 'no smoking', k: 'ban' },
            { e: '❗', n: 'exclamation', k: 'alert' },
            { e: '❕', n: 'white exclamation', k: 'alert' },
            { e: '❓', n: 'question', k: 'help' },
            { e: '❔', n: 'white question', k: 'help' },
            { e: '‼️', n: 'double exclamation', k: 'alert' },
            { e: '⁉️', n: 'exclamation question', k: 'alert' },
            { e: '🔅', n: 'dim', k: 'brightness' },
            { e: '🔆', n: 'bright', k: 'brightness' },
            { e: '〽️', n: 'part alternation', k: 'symbol' },
            { e: '⚠️', n: 'warning', k: 'alert' },
            { e: '🚸', n: 'children crossing', k: 'caution' },
            { e: '🔱', n: 'trident', k: 'symbol' },
            { e: '⚜️', n: 'fleur-de-lis', k: 'symbol' },
            { e: '🔰', n: 'japanese beginner', k: 'symbol' },
            { e: '♻️', n: 'recycling', k: 'eco' },
            { e: '✅', n: 'check mark button', k: 'done yes' },
            { e: '🈯', n: 'reserved', k: 'japanese' },
            { e: '💹', n: 'chart yen', k: 'market' },
            { e: '❇️', n: 'sparkle', k: 'symbol' },
            { e: '✳️', n: 'eight spoked asterisk', k: 'symbol' },
            { e: '❎', n: 'cross mark button', k: 'no' },
            { e: '🌐', n: 'globe meridians', k: 'world' },
            { e: '💠', n: 'diamond with a dot', k: 'symbol' },
            { e: 'Ⓜ️', n: 'circled m', k: 'metro' },
            { e: '🌀', n: 'cyclone', k: 'weather' },
            { e: '💤', n: 'zzz', k: 'sleep' },
            { e: '🏧', n: 'atm', k: 'bank' },
            { e: '🚾', n: 'wc', k: 'bathroom' },
            { e: '♿', n: 'wheelchair', k: 'access' },
            { e: '🅿️', n: 'p button', k: 'parking' },
            { e: '🛗', n: 'elevator', k: 'lift' },
            { e: '🈳', n: 'vacancy', k: 'japanese' },
            { e: '🈂️', n: 'sa', k: 'japanese' },
            { e: '🛂', n: 'passport control', k: 'travel' },
            { e: '🛃', n: 'customs', k: 'travel' },
            { e: '🛄', n: 'baggage claim', k: 'travel' },
            { e: '🛅', n: 'left luggage', k: 'travel' },
            { e: '🚹', n: 'mens', k: 'bathroom' },
            { e: '🚺', n: 'womens', k: 'bathroom' },
            { e: '🚼', n: 'baby symbol', k: 'child' },
            { e: '⚧️', n: 'transgender', k: 'symbol' },
            { e: '🚻', n: 'restroom', k: 'bathroom' },
            { e: '🚮', n: 'litter in bin', k: 'trash' },
            { e: '🎦', n: 'cinema', k: 'movie' },
            { e: '📶', n: 'signal strength', k: 'wifi' },
            { e: '🈁', n: 'here', k: 'japanese' },
            { e: '🔣', n: 'symbols', k: 'input' },
            { e: 'ℹ️', n: 'information', k: 'info' },
            { e: '🔤', n: 'abc', k: 'letters' },
            { e: '🔡', n: 'abcd', k: 'letters' },
            { e: '🔠', n: 'ABCD', k: 'letters' },
            { e: '🔢', n: '1234', k: 'numbers' },
            { e: '#️⃣', n: 'hash', k: 'number' },
            { e: '*️⃣', n: 'asterisk', k: 'star' },
            { e: '0️⃣', n: 'zero', k: 'number' },
            { e: '1️⃣', n: 'one', k: 'number' },
            { e: '2️⃣', n: 'two', k: 'number' },
            { e: '3️⃣', n: 'three', k: 'number' },
            { e: '4️⃣', n: 'four', k: 'number' },
            { e: '5️⃣', n: 'five', k: 'number' },
            { e: '6️⃣', n: 'six', k: 'number' },
            { e: '7️⃣', n: 'seven', k: 'number' },
            { e: '8️⃣', n: 'eight', k: 'number' },
            { e: '9️⃣', n: 'nine', k: 'number' },
            { e: '🔟', n: 'ten', k: 'number' },
            { e: '🔠', n: 'input latin uppercase', k: 'letters' },
            { e: '🔙', n: 'back', k: 'arrow' },
            { e: '🔚', n: 'end', k: 'arrow' },
            { e: '🔛', n: 'on', k: 'arrow' },
            { e: '🔜', n: 'soon', k: 'arrow' },
            { e: '🔝', n: 'top', k: 'arrow' },
            { e: '▶️', n: 'play', k: 'button' },
            { e: '⏸️', n: 'pause', k: 'button' },
            { e: '⏯️', n: 'play pause', k: 'button' },
            { e: '⏹️', n: 'stop', k: 'button' },
            { e: '⏺️', n: 'record', k: 'button' },
            { e: '⏭️', n: 'next track', k: 'button' },
            { e: '⏮️', n: 'last track', k: 'button' },
            { e: '⏩', n: 'fast forward', k: 'button' },
            { e: '⏪', n: 'rewind', k: 'button' },
            { e: '⏫', n: 'fast up', k: 'button' },
            { e: '⏬', n: 'fast down', k: 'button' },
            { e: '◀️', n: 'reverse', k: 'button' },
            { e: '🔼', n: 'up button', k: 'button' },
            { e: '🔽', n: 'down button', k: 'button' },
            { e: '➡️', n: 'right arrow', k: 'direction' },
            { e: '⬅️', n: 'left arrow', k: 'direction' },
            { e: '⬆️', n: 'up arrow', k: 'direction' },
            { e: '⬇️', n: 'down arrow', k: 'direction' },
            { e: '↗️', n: 'up-right arrow', k: 'direction' },
            { e: '↘️', n: 'down-right arrow', k: 'direction' },
            { e: '↙️', n: 'down-left arrow', k: 'direction' },
            { e: '↖️', n: 'up-left arrow', k: 'direction' },
            { e: '↕️', n: 'up-down arrow', k: 'direction' },
            { e: '↔️', n: 'left-right arrow', k: 'direction' },
            { e: '↩️', n: 'right arrow curving left', k: 'return' },
            { e: '↪️', n: 'left arrow curving right', k: 'forward' },
            { e: '⤴️', n: 'right arrow curving up', k: 'direction' },
            { e: '⤵️', n: 'right arrow curving down', k: 'direction' },
            { e: '🔀', n: 'shuffle', k: 'music' },
            { e: '🔁', n: 'repeat', k: 'loop' },
            { e: '🔂', n: 'repeat one', k: 'loop' },
            { e: '🔄', n: 'arrows counterclockwise', k: 'refresh' },
            { e: '🔃', n: 'arrows clockwise', k: 'reload' },
            { e: '🎵', n: 'musical note', k: 'music' },
            { e: '🎶', n: 'musical notes', k: 'music' },
            { e: '➕', n: 'plus', k: 'add' },
            { e: '➖', n: 'minus', k: 'subtract' },
            { e: '➗', n: 'divide', k: 'math' },
            { e: '✖️', n: 'multiply', k: 'math' },
            { e: '♾️', n: 'infinity', k: 'math' },
            { e: '💲', n: 'heavy dollar', k: 'money' },
            { e: '💱', n: 'currency exchange', k: 'money' },
            { e: '™️', n: 'tm', k: 'trademark' },
            { e: '©️', n: 'copyright', k: 'legal' },
            { e: '®️', n: 'registered', k: 'legal' },
            { e: '〰️', n: 'wavy dash', k: 'symbol' },
            { e: '➰', n: 'curly loop', k: 'symbol' },
            { e: '➿', n: 'double curly loop', k: 'symbol' },
            { e: '✔️', n: 'check', k: 'done yes' },
            { e: '☑️', n: 'ballot box with check', k: 'done' },
            { e: '🔘', n: 'radio button', k: 'select' },
            { e: '🔴', n: 'red circle', k: 'color' },
            { e: '🟠', n: 'orange circle', k: 'color' },
            { e: '🟡', n: 'yellow circle', k: 'color' },
            { e: '🟢', n: 'green circle', k: 'color' },
            { e: '🔵', n: 'blue circle', k: 'color' },
            { e: '🟣', n: 'purple circle', k: 'color' },
            { e: '⚫', n: 'black circle', k: 'color' },
            { e: '⚪', n: 'white circle', k: 'color' },
            { e: '🟤', n: 'brown circle', k: 'color' },
            { e: '🔺', n: 'red triangle up', k: 'shape' },
            { e: '🔻', n: 'red triangle down', k: 'shape' },
            { e: '🔸', n: 'orange diamond', k: 'shape' },
            { e: '🔹', n: 'blue diamond', k: 'shape' },
            { e: '🔶', n: 'large orange diamond', k: 'shape' },
            { e: '🔷', n: 'large blue diamond', k: 'shape' },
            { e: '🔳', n: 'white square button', k: 'shape' },
            { e: '🔲', n: 'black square button', k: 'shape' },
            { e: '▪️', n: 'black small square', k: 'shape' },
            { e: '▫️', n: 'white small square', k: 'shape' },
            { e: '◾', n: 'black medium-small square', k: 'shape' },
            { e: '◽', n: 'white medium-small square', k: 'shape' },
            { e: '◼️', n: 'black medium square', k: 'shape' },
            { e: '◻️', n: 'white medium square', k: 'shape' },
            { e: '🟥', n: 'red square', k: 'color' },
            { e: '🟧', n: 'orange square', k: 'color' },
            { e: '🟨', n: 'yellow square', k: 'color' },
            { e: '🟩', n: 'green square', k: 'color' },
            { e: '🟦', n: 'blue square', k: 'color' },
            { e: '🟪', n: 'purple square', k: 'color' },
            { e: '⬛', n: 'black large square', k: 'color' },
            { e: '⬜', n: 'white large square', k: 'color' },
            { e: '🟫', n: 'brown square', k: 'color' },
            { e: '🔈', n: 'speaker low', k: 'sound' },
            { e: '🔇', n: 'muted', k: 'sound' },
            { e: '🔉', n: 'speaker medium', k: 'sound' },
            { e: '🔊', n: 'speaker high', k: 'sound' },
            { e: '🔔', n: 'bell', k: 'notify' },
            { e: '🔕', n: 'bell slash', k: 'mute' },
            { e: '📣', n: 'mega', k: 'announce' },
            { e: '📢', n: 'loudspeaker', k: 'announce' },
            { e: '💬', n: 'speech balloon', k: 'chat' },
            { e: '💭', n: 'thought balloon', k: 'think' },
            { e: '🗯️', n: 'anger bubble', k: 'mad' },
            { e: '♠️', n: 'spade', k: 'cards' },
            { e: '♣️', n: 'club', k: 'cards' },
            { e: '♥️', n: 'heart suit', k: 'cards' },
            { e: '♦️', n: 'diamond suit', k: 'cards' },
            { e: '🃏', n: 'joker', k: 'cards' },
            { e: '🎴', n: 'flower playing cards', k: 'cards' },
            { e: '🀄', n: 'mahjong', k: 'game' },
            { e: '🕐', n: 'one oclock', k: 'time' },
            { e: '🕑', n: 'two oclock', k: 'time' },
            { e: '🕒', n: 'three oclock', k: 'time' },
            { e: '🕓', n: 'four oclock', k: 'time' },
            { e: '🕔', n: 'five oclock', k: 'time' },
            { e: '🕕', n: 'six oclock', k: 'time' },
            { e: '🕖', n: 'seven oclock', k: 'time' },
            { e: '🕗', n: 'eight oclock', k: 'time' },
            { e: '🕘', n: 'nine oclock', k: 'time' },
            { e: '🕙', n: 'ten oclock', k: 'time' },
            { e: '🕚', n: 'eleven oclock', k: 'time' },
            { e: '🕛', n: 'twelve oclock', k: 'time' },
        ],
    },
];

/** Flattened list used for search. */
export const ALL_EMOJIS: EmojiItem[] = EMOJI_CATEGORIES.flatMap((c) => c.emojis);
